create schema if not exists private;

revoke all on schema private from public;
grant usage on schema private to authenticated;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text,
  role text not null default 'trekker' check (role in ('trekker', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

create or replace function private.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.profiles
    where id = (select auth.uid())
      and role = 'admin'
  );
$$;

revoke all on function private.is_admin() from public;
grant execute on function private.is_admin() to authenticated;

revoke all on table public.profiles from anon, authenticated;
grant select on table public.profiles to authenticated;

drop policy if exists "Profiles are visible to their owners and admins" on public.profiles;
create policy "Profiles are visible to their owners and admins"
on public.profiles
for select
to authenticated
using ((select auth.uid()) = id or private.is_admin());

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, nullif(new.raw_user_meta_data ->> 'full_name', ''))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();

create table if not exists public.trek_submissions (
  id bigint generated by default as identity primary key,
  submitted_by uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name text not null,
  region text not null,
  country text not null,
  difficulty text not null check (difficulty in ('Easy', 'Moderate', 'Difficult')),
  duration_days integer not null check (duration_days > 0),
  max_altitude_m integer not null check (max_altitude_m > 0),
  distance_km integer not null check (distance_km > 0),
  best_months text[] not null default '{}',
  price_from_inr integer not null check (price_from_inr >= 0),
  risk_level text not null,
  summary text not null,
  image_url text not null,
  image_alt text not null,
  highlights text[] not null default '{}',
  essentials text[] not null default '{}',
  waypoints text[] not null default '{}',
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  admin_notes text,
  reviewed_by uuid references auth.users (id),
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.treks (
  id bigint generated by default as identity primary key,
  source_submission_id bigint unique references public.trek_submissions (id),
  slug text not null unique,
  name text not null,
  region text not null,
  country text not null,
  difficulty text not null check (difficulty in ('Easy', 'Moderate', 'Difficult')),
  duration_days integer not null check (duration_days > 0),
  max_altitude_m integer not null check (max_altitude_m > 0),
  distance_km integer not null check (distance_km > 0),
  best_months text[] not null default '{}',
  price_from_inr integer not null check (price_from_inr >= 0),
  risk_level text not null,
  summary text not null,
  image_url text not null,
  image_alt text not null,
  highlights text[] not null default '{}',
  essentials text[] not null default '{}',
  waypoints text[] not null default '{}',
  signal integer not null default 80 check (signal between 0 and 100),
  featured_rank integer not null default 100,
  published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.treks
add column if not exists source_submission_id bigint references public.trek_submissions (id);

create unique index if not exists treks_source_submission_id_key
on public.treks (source_submission_id);

alter table public.trek_submissions enable row level security;
alter table public.treks enable row level security;

revoke all on table public.trek_submissions from anon, authenticated;
grant select, insert, update on table public.trek_submissions to authenticated;

drop policy if exists "Trekkers create their own submissions" on public.trek_submissions;
create policy "Trekkers create their own submissions"
on public.trek_submissions
for insert
to authenticated
with check (
  submitted_by = (select auth.uid())
  and status = 'pending'
  and reviewed_by is null
  and reviewed_at is null
);

drop policy if exists "Trekkers read their own submissions" on public.trek_submissions;
create policy "Trekkers read their own submissions"
on public.trek_submissions
for select
to authenticated
using (submitted_by = (select auth.uid()));

drop policy if exists "Admins read every submission" on public.trek_submissions;
create policy "Admins read every submission"
on public.trek_submissions
for select
to authenticated
using (private.is_admin());

drop policy if exists "Admins review submissions" on public.trek_submissions;
create policy "Admins review submissions"
on public.trek_submissions
for update
to authenticated
using (private.is_admin())
with check (private.is_admin());

revoke all on table public.treks from anon, authenticated;
grant select on table public.treks to anon, authenticated;
grant insert, update, delete on table public.treks to authenticated;

drop policy if exists "Published treks are public" on public.treks;
create policy "Published treks are public"
on public.treks
for select
to anon, authenticated
using (published = true);

drop policy if exists "Admins read every trek" on public.treks;
create policy "Admins read every trek"
on public.treks
for select
to authenticated
using (private.is_admin());

drop policy if exists "Admins manage treks" on public.treks;
create policy "Admins manage treks"
on public.treks
for all
to authenticated
using (private.is_admin())
with check (private.is_admin());

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists touch_profiles_updated_at on public.profiles;
create trigger touch_profiles_updated_at
before update on public.profiles
for each row
execute function public.touch_updated_at();

drop trigger if exists touch_submissions_updated_at on public.trek_submissions;
create trigger touch_submissions_updated_at
before update on public.trek_submissions
for each row
execute function public.touch_updated_at();

drop trigger if exists touch_treks_updated_at on public.treks;
create trigger touch_treks_updated_at
before update on public.treks
for each row
execute function public.touch_updated_at();

create or replace function public.publish_submission(target_submission_id bigint)
returns bigint
language plpgsql
security definer
set search_path = public, private
as $$
declare
  candidate public.trek_submissions%rowtype;
  published_trek_id bigint;
  slug_base text;
begin
  if not private.is_admin() then
    raise exception 'Admin access required';
  end if;

  select *
  into candidate
  from public.trek_submissions
  where id = target_submission_id;

  if not found then
    raise exception 'Submission not found';
  end if;

  slug_base := trim(both '-' from regexp_replace(lower(candidate.name), '[^a-z0-9]+', '-', 'g'));

  if slug_base = '' then
    slug_base := 'trek';
  end if;

  insert into public.treks (
    source_submission_id,
    slug,
    name,
    region,
    country,
    difficulty,
    duration_days,
    max_altitude_m,
    distance_km,
    best_months,
    price_from_inr,
    risk_level,
    summary,
    image_url,
    image_alt,
    highlights,
    essentials,
    waypoints,
    published
  )
  values (
    candidate.id,
    slug_base || '-' || candidate.id::text,
    candidate.name,
    candidate.region,
    candidate.country,
    candidate.difficulty,
    candidate.duration_days,
    candidate.max_altitude_m,
    candidate.distance_km,
    candidate.best_months,
    candidate.price_from_inr,
    candidate.risk_level,
    candidate.summary,
    candidate.image_url,
    candidate.image_alt,
    candidate.highlights,
    candidate.essentials,
    candidate.waypoints,
    true
  )
  on conflict (source_submission_id) do update set
    name = excluded.name,
    region = excluded.region,
    country = excluded.country,
    difficulty = excluded.difficulty,
    duration_days = excluded.duration_days,
    max_altitude_m = excluded.max_altitude_m,
    distance_km = excluded.distance_km,
    best_months = excluded.best_months,
    price_from_inr = excluded.price_from_inr,
    risk_level = excluded.risk_level,
    summary = excluded.summary,
    image_url = excluded.image_url,
    image_alt = excluded.image_alt,
    highlights = excluded.highlights,
    essentials = excluded.essentials,
    waypoints = excluded.waypoints,
    published = true
  returning id into published_trek_id;

  update public.trek_submissions
  set
    status = 'approved',
    reviewed_by = (select auth.uid()),
    reviewed_at = now()
  where id = candidate.id;

  return published_trek_id;
end;
$$;

revoke all on function public.publish_submission(bigint) from public;
grant execute on function public.publish_submission(bigint) to authenticated;
