insert into public.treks (
  slug,
  name,
  region,
  country,
  difficulty,
  duration_days,
  max_altitude_m,
  distance_km,
  best_months,
  price_from_inr,
  risk_level,
  summary,
  image_url,
  image_alt,
  highlights,
  essentials,
  waypoints,
  signal,
  featured_rank,
  published
)
values
(
  'hampta-pass',
  'Hampta Pass',
  'Himachal',
  'India',
  'Moderate',
  5,
  4270,
  26,
  array['Jun', 'Jul', 'Aug', 'Sep'],
  10900,
  'Weather shifts',
  'A compact crossover from green Kullu valleys to the stark Lahaul side, with river crossings and a high pass day.',
  'https://images.unsplash.com/photo-1454496522488-7a8e488e8606?auto=format&fit=crop&w=1600&q=80',
  'Snow ridges above a mountain trekking route',
  array['Pass crossing', 'Chandratal extension', 'Valley contrast'],
  array['Layered rain protection', 'Trekking poles', 'Acclimatization buffer'],
  array['Jobra', 'Chika', 'Balu Ka Ghera', 'Shea Goru', 'Chatru'],
  92,
  1,
  true
),
(
  'kedarkantha',
  'Kedarkantha',
  'Uttarakhand',
  'India',
  'Easy',
  6,
  3810,
  20,
  array['Dec', 'Jan', 'Feb', 'Mar', 'Apr'],
  7990,
  'Snow exposure',
  'A winter-friendly summit trek with forest camps, broad ridgelines, and a sunrise push that rewards steady pacing.',
  'https://images.unsplash.com/photo-1491555103944-7c647fd857e6?auto=format&fit=crop&w=1600&q=80',
  'Hikers moving across a snowy mountain landscape',
  array['Summit sunrise', 'Pine camps', 'Beginner snow terrain'],
  array['Insulated boots', 'Thermal layers', 'Headlamp'],
  array['Sankri', 'Juda Ka Talab', 'Base Camp', 'Summit', 'Hargaon'],
  88,
  2,
  true
),
(
  'rupin-pass',
  'Rupin Pass',
  'Himachal',
  'India',
  'Difficult',
  8,
  4650,
  52,
  array['May', 'Jun', 'Sep', 'Oct'],
  18900,
  'Pass day load',
  'A dramatic progression through hanging villages, waterfalls, snowfields, and a steep pass crossing into Sangla.',
  'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1600&q=80',
  'High mountain ridge above a trekking route',
  array['Waterfall amphitheater', 'Snow gullies', 'Village trail'],
  array['Strong endurance', 'Microspike readiness', 'Weather reserve'],
  array['Jiskun', 'Jakha', 'Dhanderas Thatch', 'Upper Waterfall', 'Ronti Gad'],
  95,
  3,
  true
),
(
  'tarsar-marsar',
  'Tarsar Marsar',
  'Kashmir',
  'India',
  'Moderate',
  7,
  4115,
  48,
  array['Jul', 'Aug', 'Sep'],
  15900,
  'Lake weather',
  'A lake-led route through meadows and passes where camps are shaped by water, wind, and wide Kashmir views.',
  'https://images.unsplash.com/photo-1486911278844-a81c5267e227?auto=format&fit=crop&w=1600&q=80',
  'Alpine lake beneath green mountains',
  array['Twin lakes', 'Meadow camps', 'Pass panoramas'],
  array['Waterproof camp kit', 'Sun protection', 'Cold evening layers'],
  array['Aru', 'Lidderwat', 'Shekwas', 'Tarsar', 'Sumbal'],
  91,
  4,
  true
),
(
  'sandakhphu',
  'Sandakphu',
  'West Bengal',
  'India',
  'Easy',
  6,
  3636,
  46,
  array['Mar', 'Apr', 'May', 'Oct', 'Nov'],
  12900,
  'Wind chill',
  'A tea-house style ridge walk with rhododendron seasons and long views toward the eastern Himalaya.',
  'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1600&q=80',
  'Mountain ridge beneath a clear starry sky',
  array['Sleeping Buddha view', 'Ridge villages', 'Rhododendrons'],
  array['Wind shell', 'Cash for trail stops', 'Trail shoes'],
  array['Manebhanjan', 'Tumling', 'Kalipokhri', 'Sandakphu', 'Gurdum'],
  84,
  5,
  true
),
(
  'gokyo-lakes',
  'Gokyo Lakes',
  'Khumbu',
  'Nepal',
  'Difficult',
  12,
  5357,
  92,
  array['Mar', 'Apr', 'May', 'Oct', 'Nov'],
  64900,
  'Altitude management',
  'A high Khumbu route built around turquoise lakes, acclimatization discipline, and a summit view from Gokyo Ri.',
  'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1600&q=80',
  'Trekkers overlooking a broad Himalayan valley',
  array['Gokyo Ri', 'Glacial lakes', 'Khumbu villages'],
  array['Acclimatization plan', 'Insurance check', 'Down layers'],
  array['Lukla', 'Namche', 'Dole', 'Machhermo', 'Gokyo'],
  97,
  6,
  true
)
on conflict (slug) do update set
  name = excluded.name,
  region = excluded.region,
  country = excluded.country,
  difficulty = excluded.difficulty,
  duration_days = excluded.duration_days,
  max_altitude_m = excluded.max_altitude_m,
  distance_km = excluded.distance_km,
  best_months = excluded.best_months,
  price_from_inr = excluded.price_from_inr,
  risk_level = excluded.risk_level,
  summary = excluded.summary,
  image_url = excluded.image_url,
  image_alt = excluded.image_alt,
  highlights = excluded.highlights,
  essentials = excluded.essentials,
  waypoints = excluded.waypoints,
  signal = excluded.signal,
  featured_rank = excluded.featured_rank,
  published = excluded.published;
